--- #YAML:1.0
name:               Dancer-Template-Tenjin
version:            0.3
abstract:           Tenjin wrapper for Dancer
author:
    - Ido Perlmuter <ido@ido50.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Dancer:      1.15
    Tenjin:      0.051
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
